services:
  app:
    build: ./app
    command: python src/views.py
    volumes:
      - ./app:/app
    container_name: lab-app
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: postgres
    expose:
      - "5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    container_name: lab-db
    volumes:
      - postgresql_volume:/var/lib/postgresql/data/

volumes:
  postgresql_volume:
